/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { useAnimations } from '@react-three/drei/core/useAnimations'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useLoader, useFrame } from 'react-three-fiber'

export default function Model(props) {
  const group = useRef(null)
  const { nodes, materials, animations } = useGLTF(
    '/assets/auto.glb'
  ) 

  function AnimationController(props) {
    const { actions } = useAnimations(props.animations, props.ybotRef)
    // const { actions } = useAnimations<GLTFActions>(animations, group)

    console.log(actions)




    return null
  }


  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box005.geometry}
          material={materials.M_Auto}
          position={[182.418655, 0, 57.63814]}
          rotation={[0, 0.674054, 0]}
          userData={{ name: 'Box005' }}
        />
        <AnimationController ybotRef={group} animations={animations} />
      </group>
    </>
  )
}

useGLTF.preload('/auto.glb')
