/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { Canvas, useFrame } from '@react-three/fiber'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useSpring } from '@react-spring/three'

import { a } from "@react-spring/three";

export default function Model(props) {
  const vec = new THREE.Vector3()
  const [active, setActive] = useState(false)
  const [zoom, set] = useState(false)


  useEffect(() => {
    document.body.style.cursor = active ? 'pointer' : 'auto'},
    [active])

  useEffect(() => {
      props.setTest(zoom);
  },[zoom])


  useFrame((state) => {
    if(props.test){
    // const step = 0.1
    // state.camera.position.lerp(vec.set(25, 1,  0), step)
    // state.camera.lookAt(-114.292229 , 0 , -72.47771)
    // state.camera.updateProjectionMatrix()
    }
    else {
      
      // const step = 0.04
      // state.camera.position.lerp(vec.set(250, 200,  250), step)
      // state.camera.lookAt(0 , 0 , 0)

      // state.camera.updateProjectionMatrix()
    }
  })

  const group = useRef(null)

  const { nodes, materials } = useGLTF(
    '/assets/compressed-haasjeover.glb'
  ) 
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-114.292229, 0, -72.47771]}
        rotation={[0, -0.4974189, 0]}
        userData={{ name: 'StrijpS_Gebouw_01', body: 'haasje over text' }}
        onClick={() => set(!zoom)} onPointerOver={() => setActive(true)} onPointerOut={() => setActive(false)}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StrijpS_Gebouw_01_1.geometry}
          material={materials.M_Gebouw_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StrijpS_Gebouw_01_2.geometry}
          material={materials.M_5060Faces_directUnwrap_Windows}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/compressed-haasjeover.glb')
