/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    StrijpS_Gebouw_01_1: THREE.Mesh
    StrijpS_Gebouw_01_2: THREE.Mesh
  }
  materials: {
    M_Gebouw_01: THREE.MeshStandardMaterial
    M_5060Faces_directUnwrap_Windows: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    '/assets/StrijpS_Gebouw_01.glb'
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-114.292229, 0, -72.47771]}
        rotation={[0, -0.4974189, 0]}
        userData={{ name: 'StrijpS_Gebouw_01' }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StrijpS_Gebouw_01_1.geometry}
          material={materials.M_Gebouw_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StrijpS_Gebouw_01_2.geometry}
          material={materials.M_5060Faces_directUnwrap_Windows}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/StrijpS_Gebouw_01.glb')
